### ISSUE TITLE
`lipisha/sdk v1.0 requires ext-curl ^0.0.0 -> the requested PHP extension curl has the wrong version (7.3.4) installed

### ISSUE THREAD

**Issue by davidsitati** [lipisha/lipisha-php-sdk#10]
`lipisha/sdk v1.0 requires ext-curl ^0.0.0 -> the requested PHP extension curl has the wrong version (7.3.4) installed.`

It still brings this error. Any solutions?

**Comment by martqasomo** [comment]
Fixed issue. Allow ext-curl *. Updated composer.
