### ISSUE TITLE
Doesn't work with php 7

### ISSUE THREAD

**Issue by PhillipMwaniki** [lipisha/lipisha-php-sdk#2]
i have PHP 7 installed on an ubuntu server with curl. I keep getting a curl not found error each time I install the package. Could you please switch it to a guzzle request or give a URL I can directly post to.

![lipisha error](https://cloud.githubusercontent.com/assets/2037708/18647728/14026008-7ec0-11e6-91a0-c24b240dc4ff.png)

**Comment by thomas-tewelde** [comment]
i have the same issue when i upgraded to php 7 ... where you able to fix this

**Comment by PhillipMwaniki** [comment]
Pick out the method from the Lipisha.php file and implement it using guzzle. It's easy that way.

**Comment by thomas-tewelde** [comment]
i just downgraded php to 5.6 ... i will attempt your solution

**Comment by wangombe-g** [comment]
Has no one solved this issue? Also can't use this SDK using PHP 7

**Comment by NicholasKimuli** [comment]
A simple change to the composer.json file requiring any version of ext-curl would sort the issue. @rithi please check out the proposed change?

     `"require": {
         "php": ">=5.3.0",
         "ext-curl": "^0.0.0" // From this
         "ext-curl": "*" // To this
     },
     "require-dev":{
        "ext-curl":"^0.0.0" // Same here
     }`

**Comment by donmarsh** [comment]
composer.json has been updated. Thank you.
