### ISSUE TITLE
issue with php 7?

### ISSUE THREAD

**Issue by wyklif** [lipisha/lipisha-php-sdk#3]
i am getting this when trying to do a composer install on a new ubuntu 14.04 server

 Installation request for lipisha/sdk v1.0 -> satisfiable by lipisha/sdk[v1.0].
    - lipisha/sdk v1.0 requires ext-curl ^0.0.0 -> the requested PHP extension curl has the wrong version (7.0.14-2+deb.sury.org~trusty+1) installed.
please assist urgent

**Comment by donmarsh** [comment]
composer.json has been updated and should work. Thank you.
