### ISSUE TITLE
Cannot  work in  Laravel 5. 4

### ISSUE THREAD

**Issue by Bkoech** [lipisha/lipisha-php-sdk#4]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for lipisha/sdk ^1.0 -> satisfiable by lipisha/sdk[v1.0].
    - lipisha/sdk v1.0 requires ext-curl ^0.0.0 -> the requested PHP extension curl has the wrong version (7.1.3) installed.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp64\bin\php\php7.1.3\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by donmarsh** [comment]
composer.json has been updated and should work well now. Thank you.
