### ISSUE TITLE
Requires ext-curl ^0.0.0 even after composer.json update

### ISSUE THREAD

**Issue by petersephrin** [lipisha/lipisha-php-sdk#5]
I saw the update on the composer.json file but still the same problem comes up. Please check if you have updated on packagist

**Comment by Mbanya** [comment]
Same issue as the one above.
**Error Message:**
_lipisha/sdk v1.0 requires ext-curl ^0.0.0 -> the requested PHP extension curl has the wrong version_

**Comment by jkoech** [comment]
Also getting the same issue on windows 10 using XAMPP with php 7.

**Comment by martqasomo** [comment]
Fixed issue. Allow ext-curl *. Updated composer.
